schema: "classroom50/repo-config/v1"
classroom: "hbui-cs312-f26"
assignment: "lab3"
owner:
  username: "ColtenHargett"
  id: 230263284
  accepted_at: "2026-09-22T13:28:56Z"
source:
  owner: "hbui-cs312-f26"
  owner_id: 317684957
  repo: "lab03-template"
  branch: "main"
