schema: "classroom50/repo-config/v1"
classroom: "hbui-cs312-f26"
assignment: "pa1"
owner:
  username: "ColtenHargett"
  id: 230263284
  accepted_at: "2026-09-14T00:52:52Z"
source:
  owner: "hbui-cs312-f26"
  owner_id: 317684957
  repo: "pa1-template"
  branch: "main"
