schema: "classroom50/repo-config/v1"
classroom: "hbui-cs312-f26"
assignment: "lab1"
owner:
  username: "ColtenHargett"
  id: 230263284
  accepted_at: "2026-09-08T13:34:08Z"
source:
  owner: "hbui-cs312-f26"
  owner_id: 317684957
  repo: "lab01-template"
  branch: "main"
